### PR TITLE
Better deal with uneval nodes

### LINKED ISSUE #20: 1.8.1 Execution error
```{:clojure.main/message
 "Execution error (UnsupportedOperationException) at rewrite_clj.node.uneval.UnevalNode/sexpr (uneval.clj:6).\nnull\n",
 :clojure.main/triage
 {:clojure.error/class java.lang.UnsupportedOperationException,
  :clojure.error/line 6,
  :clojure.error/symbol rewrite_clj.node.uneval.UnevalNode/sexpr,
  :clojure.error/source "uneval.clj",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type java.lang.UnsupportedOperationException,
    :at [rewrite_clj.node.uneval.UnevalNode sexpr "uneval.clj" 6]}],
  :trace
  [[rewrite_clj.node.uneval.UnevalNode sexpr "uneval.clj" 6]
   [rewrite_clj.zip.base$sexpr invokeStatic "base.clj" 49]
   [rewrite_clj.zip.base$sexpr invoke "base.clj" 46]
   [depot.zip$lib_QMARK_ invokeStatic "zip.clj" 100]
   [depot.zip$lib_QMARK_ invoke "zip.clj" 94]
   [clojure.core$complement$fn__5671 invoke "core.clj" 1441]
   [clojure.core$drop_while$step__5942 invoke "core.clj" 2974]
   [clojure.core$drop_while$fn__5945 invoke "core.clj" 2977]
   [clojure.lang.LazySeq sval "LazySeq.java" 42]
   [clojure.lang.LazySeq seq "LazySeq.java" 51]
   [clojure.lang.LazySeq first "LazySeq.java" 73]
   [clojure.lang.RT first "RT.java" 692]
   [clojure.core$first__5386 invokeStatic "core.clj" 55]
   [clojure.core$first__5386 invoke "core.clj" 55]
   [rewrite_clj.zip.find$find invokeStatic "find.clj" 33]
   [rewrite_clj.zip.find$find invoke "find.clj" 21]
   [rewrite_clj.zip.find$find_next invokeStatic "find.clj" 48]
   [rewrite_clj.zip.find$find_next invoke "find.clj" 41]
   [rewrite_clj.zip.find$find_next_depth_first
    invokeStatic
    "find.clj"
    55]
   [rewrite_clj.zip.find$find_next_depth_first invoke "find.clj" 50]
   [depot.zip$next_lib invokeStatic "zip.clj" 108]
   [depot.zip$next_lib invoke "zip.clj" 105]
   [depot.zip$transform_libs invokeStatic "zip.clj" 136]
   [depot.zip$transform_libs doInvoke "zip.clj" 131]
   [clojure.lang.RestFn invoke "RestFn.java" 425]
   [depot.outdated.resolve_virtual$resolve_all
    invokeStatic
    "resolve_virtual.clj"
    20]
   [depot.outdated.resolve_virtual$resolve_all
    invoke
    "resolve_virtual.clj"
    18]
   [depot.outdated.resolve_virtual$update_deps_edn_BANG_
    invokeStatic
    "resolve_virtual.clj"
    39]
   [depot.outdated.resolve_virtual$update_deps_edn_BANG_
    invoke
    "resolve_virtual.clj"
    34]
   [depot.outdated.main$_main invokeStatic "main.clj" 52]
   [depot.outdated.main$_main doInvoke "main.clj" 33]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.core$apply invokeStatic "core.clj" 665]
   [clojure.main$main_opt invokeStatic "main.clj" 514]
   [clojure.main$main_opt invoke "main.clj" 510]
   [clojure.main$main invokeStatic "main.clj" 665]
   [clojure.main$main doInvoke "main.clj" 618]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]]}}

```

Works fine on 1.8.0

### PR DESCRIPTION
**Pull request by plexus**
We now have our own versions of left/right/next that all correctly jump over
uneval nodes, in particular we want to avoid descending into uneval subtrees (as
they may contain gibberish), or call sexp on an uneval node (as that will
outright fail).

See https://github.com/xsc/rewrite-clj/issues/70

Closes #20

### CODE REVIEW

File: src/depot/zip.clj [hunk 1]
```diff
@@ -5,25 +5,34 @@
...
+  (loop [loc loc]
+    (cond
+      (nil? loc) loc
+      (end?-fn loc) loc
+
+      (#{:comment :whitespace :newline :comma} (rzip/tag loc))
+      (recur (next-fn loc))
+
+      (= :uneval (rzip/tag loc))
+      (recur (skip-fn loc))
```
Comment (Olical) [inline src/depot/zip.clj:18]: Ah, makes sense, glad it's pretty well telegraphed as `uneval`. By `uneval` do you mean the `#_` reader macro? Wasn't sure what the name meant exactly.

**Review by Olical — APPROVED** [review]

**Comment by Olical** [comment]
Released under `v1.8.2`.

File: src/depot/zip.clj (hunk 1 above)
Comment (plexus) [reply src/depot/zip.clj:18]: exactly, uneval == `#_ ...`
